import type {SQLInputValue,SQLOutputValue} from 'node:sqlite';
export interface CandidateArtifactRow {principalId:string;id:string;planId:string;resultId:string;snapshotDigest:string;treeDigest:string;artifactDigest:string;createdAt:number}
export interface CandidateOutcomeRow {principalId:string;id:string;artifactId:string;missionId:string;artifactDigest:string;createdAt:number}
const hash=(c:string)=>`length(${c})=64 AND ${c} NOT GLOB '*[^0-9a-f]*'`;
export const CANDIDATE_ARTIFACT_SCHEMA=[
  `CREATE TABLE candidate_artifacts(principal_id TEXT NOT NULL,id TEXT NOT NULL,artifact_kind TEXT NOT NULL DEFAULT 'artifact' CHECK(artifact_kind='artifact'),plan_id TEXT NOT NULL,result_id TEXT NOT NULL,snapshot_digest TEXT NOT NULL CHECK(${hash('snapshot_digest')}),tree_digest TEXT NOT NULL CHECK(${hash('tree_digest')}),artifact_digest TEXT NOT NULL CHECK(${hash('artifact_digest')}),created_at INTEGER NOT NULL CHECK(created_at BETWEEN 0 AND 9007199254740991),PRIMARY KEY(principal_id,id),UNIQUE(principal_id,plan_id),FOREIGN KEY(principal_id,id,artifact_kind) REFERENCES record_heads(principal_id,id,kind),FOREIGN KEY(principal_id,plan_id) REFERENCES candidate_evaluation_plans(principal_id,id),FOREIGN KEY(principal_id,result_id) REFERENCES candidate_evaluation_results(principal_id,id)) STRICT`,
  `CREATE TRIGGER candidate_artifact_binding BEFORE INSERT ON candidate_artifacts WHEN NOT EXISTS(SELECT 1 FROM candidate_evaluation_results r JOIN candidate_evaluation_attempts a ON a.principal_id=r.principal_id AND a.id=r.attempt_id JOIN candidate_evaluation_plans p ON p.principal_id=a.principal_id AND p.id=a.plan_id JOIN candidate_proposals c ON c.principal_id=p.principal_id AND c.id=p.proposal_id WHERE r.principal_id=NEW.principal_id AND r.id=NEW.result_id AND r.status='passed' AND p.id=NEW.plan_id AND c.after_digest=NEW.snapshot_digest AND c.after_tree_digest=NEW.tree_digest AND NEW.created_at>=r.created_at) BEGIN SELECT RAISE(ABORT,'candidate artifact evaluation mismatch'); END`,
  `CREATE TRIGGER candidate_artifact_data BEFORE INSERT ON candidate_artifacts WHEN NOT EXISTS(SELECT 1 FROM record_heads h JOIN record_versions v ON v.principal_id=h.principal_id AND v.version_id=h.current_version_id WHERE h.principal_id=NEW.principal_id AND h.id=NEW.id AND h.kind='artifact' AND json_extract(v.data,'$.format')='candidate_artifact_v1' AND json_extract(v.data,'$.verification')='candidate_verified' AND json_extract(v.data,'$.planId')=NEW.plan_id AND json_extract(v.data,'$.resultId')=NEW.result_id AND json_extract(v.data,'$.snapshot.digest')=NEW.snapshot_digest AND json_extract(v.data,'$.snapshot.treeDigest')=NEW.tree_digest AND json_extract(v.data,'$.artifactDigest')=NEW.artifact_digest) BEGIN SELECT RAISE(ABORT,'candidate artifact data mismatch'); END`,
  `CREATE TRIGGER candidate_artifact_immutable_update BEFORE UPDATE ON candidate_artifacts BEGIN SELECT RAISE(ABORT,'candidate artifact binding immutable'); END`,
  `CREATE TRIGGER candidate_artifact_immutable_delete BEFORE DELETE ON candidate_artifacts BEGIN SELECT RAISE(ABORT,'candidate artifact binding immutable'); END`,
];
export const CANDIDATE_OUTCOME_SCHEMA=[
  `CREATE TABLE candidate_outcomes(principal_id TEXT NOT NULL,id TEXT NOT NULL,outcome_kind TEXT NOT NULL DEFAULT 'outcome' CHECK(outcome_kind='outcome'),artifact_id TEXT NOT NULL,mission_id TEXT NOT NULL,artifact_digest TEXT NOT NULL CHECK(${hash('artifact_digest')}),created_at INTEGER NOT NULL CHECK(created_at BETWEEN 0 AND 9007199254740991),PRIMARY KEY(principal_id,id),UNIQUE(principal_id,artifact_id),FOREIGN KEY(principal_id,id,outcome_kind) REFERENCES record_heads(principal_id,id,kind),FOREIGN KEY(principal_id,artifact_id) REFERENCES candidate_artifacts(principal_id,id),FOREIGN KEY(principal_id,mission_id) REFERENCES scopes(principal_id,id)) STRICT`,
  `CREATE TRIGGER candidate_outcome_binding BEFORE INSERT ON candidate_outcomes WHEN NOT EXISTS(SELECT 1 FROM candidate_artifacts a JOIN candidate_evaluation_plans p ON p.principal_id=a.principal_id AND p.id=a.plan_id JOIN record_heads ph ON ph.principal_id=p.principal_id AND ph.id=p.id JOIN record_versions pv ON pv.principal_id=ph.principal_id AND pv.version_id=ph.current_version_id JOIN record_heads h ON h.principal_id=a.principal_id AND h.id=NEW.id JOIN record_versions v ON v.principal_id=h.principal_id AND v.version_id=h.current_version_id WHERE a.principal_id=NEW.principal_id AND a.id=NEW.artifact_id AND a.artifact_digest=NEW.artifact_digest AND NEW.created_at>=a.created_at AND json_extract(pv.data,'$.plan.missionId')=NEW.mission_id AND h.kind='outcome' AND json_extract(v.data,'$.artifactId')=a.id AND json_extract(v.data,'$.missionId')=NEW.mission_id AND json_extract(v.data,'$.verification')='candidate_verified' AND json_extract(v.data,'$.state')='pending' AND json_extract(v.data,'$.explanationRevision')='1') BEGIN SELECT RAISE(ABORT,'candidate outcome binding mismatch'); END`,
  `CREATE TRIGGER candidate_outcome_immutable_update BEFORE UPDATE ON candidate_outcomes BEGIN SELECT RAISE(ABORT,'candidate outcome binding immutable'); END`,
  `CREATE TRIGGER candidate_outcome_immutable_delete BEFORE DELETE ON candidate_outcomes BEGIN SELECT RAISE(ABORT,'candidate outcome binding immutable'); END`,
];
export interface CandidateArtifactReader {get(p:string,id:string):CandidateArtifactRow|undefined;forPlan(p:string,id:string):CandidateArtifactRow|undefined;outcome(p:string,id:string):CandidateOutcomeRow|undefined;outcomeForArtifact(p:string,id:string):CandidateOutcomeRow|undefined}
export interface CandidateArtifactTransaction extends CandidateArtifactReader {insert(row:CandidateArtifactRow):void;insertOutcome(row:CandidateOutcomeRow):void}
type Row=Record<string,SQLOutputValue>;
type Get=(sql:string,...args:SQLInputValue[])=>Row|undefined;
type Run=(sql:string,...args:SQLInputValue[])=>unknown;
export class CandidateArtifactAccess implements CandidateArtifactTransaction {
  #query:Get;#run:Run;
  constructor(query:Get,run:Run){this.#query=query;this.#run=run;}
  #row(r:Row|undefined):CandidateArtifactRow|undefined{return r&&{principalId:r.principal_id as string,id:r.id as string,planId:r.plan_id as string,resultId:r.result_id as string,snapshotDigest:r.snapshot_digest as string,treeDigest:r.tree_digest as string,artifactDigest:r.artifact_digest as string,createdAt:Number(r.created_at)}}
  get(p:string,id:string){return this.#row(this.#query('SELECT * FROM candidate_artifacts WHERE principal_id=? AND id=?',p,id));}
  forPlan(p:string,id:string){return this.#row(this.#query('SELECT * FROM candidate_artifacts WHERE principal_id=? AND plan_id=?',p,id));}
  insert(r:CandidateArtifactRow){this.#run('INSERT INTO candidate_artifacts(principal_id,id,plan_id,result_id,snapshot_digest,tree_digest,artifact_digest,created_at) VALUES(?,?,?,?,?,?,?,?)',r.principalId,r.id,r.planId,r.resultId,r.snapshotDigest,r.treeDigest,r.artifactDigest,r.createdAt);}
  #outcome(r:Row|undefined):CandidateOutcomeRow|undefined{return r&&{principalId:r.principal_id as string,id:r.id as string,artifactId:r.artifact_id as string,missionId:r.mission_id as string,artifactDigest:r.artifact_digest as string,createdAt:Number(r.created_at)}}
  outcome(p:string,id:string){return this.#outcome(this.#query('SELECT * FROM candidate_outcomes WHERE principal_id=? AND id=?',p,id));}
  outcomeForArtifact(p:string,id:string){return this.#outcome(this.#query('SELECT * FROM candidate_outcomes WHERE principal_id=? AND artifact_id=?',p,id));}
  insertOutcome(r:CandidateOutcomeRow){this.#run('INSERT INTO candidate_outcomes(principal_id,id,artifact_id,mission_id,artifact_digest,created_at) VALUES(?,?,?,?,?,?)',r.principalId,r.id,r.artifactId,r.missionId,r.artifactDigest,r.createdAt);}
}
