import type { SQLInputValue, SQLOutputValue } from 'node:sqlite';

export type RunnerEvidenceKind = 'synthetic' | 'fixed_guest_fixture';
export interface RunnerProfile { principalId: string; id: string; revision: bigint; digest: string; kind: RunnerEvidenceKind; isolationId: string; ttlMs: number }
export interface RunnerWorkspace { principalId: string; id: string; profileId: string; profileRevision: bigint; profileDigest: string; snapshotDigest: string; writeSetDigest: string; isolationId: string; generation: bigint; state: 'ready' | 'quarantined' }
export interface RunnerLease { principalId: string; id: string; workspaceId: string; generation: bigint; scopeId: string; actorId: string; ownerId: string; ownerEpoch: bigint; stopEpoch: bigint; operation: 'verify'; state: 'active' | 'stop_requested' | 'quarantined' | 'released'; revision: bigint; sequence: bigint; expiresAt: number; hardDeadline: number; updatedAt: number; dispatched: boolean; observationId: string | null }
export interface RunnerStopObservation { principalId: string; id: string; leaseId: string; workspaceId: string; generation: bigint; ownerId: string; ownerEpoch: bigint; stopEpoch: bigint; kind: RunnerEvidenceKind; handlesSignaled: boolean; jobEmpty: boolean; writesStable: boolean; observedAt: number; detail: string }
const epoch = 'BETWEEN 1 AND 999999999999999999';
const hash = (column: string) => `length(${column})=64 AND ${column} NOT GLOB '*[^0-9a-f]*'`;
const binding = 'principal_id,lease_id,workspace_id,generation,owner_id,owner_epoch,stop_epoch';
export const RUNNER_SCHEMA = [
  `CREATE TABLE runner_profiles(principal_id TEXT NOT NULL REFERENCES principals(id), id TEXT NOT NULL, revision INTEGER NOT NULL CHECK(revision ${epoch}), digest TEXT NOT NULL CHECK(${hash('digest')}), kind TEXT NOT NULL CHECK(kind IN ('synthetic','fixed_guest_fixture')), isolation_id TEXT NOT NULL, ttl_ms INTEGER NOT NULL CHECK(ttl_ms BETWEEN 100 AND 60000), PRIMARY KEY(principal_id,id,revision), UNIQUE(principal_id,id,revision,digest,isolation_id)) STRICT`,
  `CREATE TRIGGER runner_profile_update BEFORE UPDATE ON runner_profiles BEGIN SELECT RAISE(ABORT,'runner profile is immutable'); END`,
  `CREATE TRIGGER runner_profile_delete BEFORE DELETE ON runner_profiles BEGIN SELECT RAISE(ABORT,'runner profile is immutable'); END`,
  `CREATE TABLE runner_workspaces(principal_id TEXT NOT NULL REFERENCES principals(id), id TEXT PRIMARY KEY, profile_id TEXT NOT NULL, profile_revision INTEGER NOT NULL, profile_digest TEXT NOT NULL, snapshot_digest TEXT NOT NULL CHECK(${hash('snapshot_digest')}), write_set_digest TEXT NOT NULL CHECK(${hash('write_set_digest')}), isolation_id TEXT NOT NULL, generation INTEGER NOT NULL CHECK(generation ${epoch}), state TEXT NOT NULL CHECK(state IN ('ready','quarantined')), UNIQUE(principal_id,id), FOREIGN KEY(principal_id,profile_id,profile_revision,profile_digest,isolation_id) REFERENCES runner_profiles(principal_id,id,revision,digest,isolation_id)) STRICT`,
  `CREATE TRIGGER runner_workspace_update BEFORE UPDATE ON runner_workspaces WHEN NEW.principal_id!=OLD.principal_id OR NEW.id!=OLD.id OR NEW.profile_id!=OLD.profile_id OR NEW.profile_revision!=OLD.profile_revision OR NEW.profile_digest!=OLD.profile_digest OR NEW.snapshot_digest!=OLD.snapshot_digest OR NEW.write_set_digest!=OLD.write_set_digest OR NEW.isolation_id!=OLD.isolation_id OR NEW.generation<OLD.generation OR NEW.generation>OLD.generation+1 BEGIN SELECT RAISE(ABORT,'workspace binding/generation mismatch'); END`,
  `CREATE TABLE runner_leases(principal_id TEXT NOT NULL, id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, generation INTEGER NOT NULL CHECK(generation ${epoch}), scope_id TEXT NOT NULL, actor_id TEXT NOT NULL, owner_id TEXT NOT NULL, owner_epoch INTEGER NOT NULL CHECK(owner_epoch ${epoch}), stop_epoch INTEGER NOT NULL CHECK(stop_epoch IN (0,1)), operation TEXT NOT NULL CHECK(operation='verify'), state TEXT NOT NULL CHECK(state IN ('active','stop_requested','quarantined','released')), revision INTEGER NOT NULL CHECK(revision ${epoch}), sequence INTEGER NOT NULL CHECK(sequence BETWEEN 0 AND 999999999999999999), expires_at INTEGER NOT NULL CHECK(expires_at BETWEEN 0 AND 9007199254740991), hard_deadline INTEGER NOT NULL CHECK(hard_deadline BETWEEN expires_at AND 9007199254740991), updated_at INTEGER NOT NULL CHECK(updated_at BETWEEN 0 AND 9007199254740991), dispatched INTEGER NOT NULL CHECK(dispatched IN (0,1)), observation_id TEXT, CHECK((state='active' AND stop_epoch=0 AND observation_id IS NULL) OR (state IN ('stop_requested','quarantined') AND stop_epoch=1 AND observation_id IS NULL) OR (state='released' AND observation_id IS NOT NULL)), UNIQUE(${binding.replace('lease_id','id')}), FOREIGN KEY(principal_id,workspace_id) REFERENCES runner_workspaces(principal_id,id), FOREIGN KEY(principal_id,scope_id) REFERENCES scopes(principal_id,id), FOREIGN KEY(principal_id,actor_id) REFERENCES memberships(principal_id,actor_id), FOREIGN KEY(principal_id,observation_id) REFERENCES runner_stop_observations(principal_id,id)) STRICT`,
  `CREATE UNIQUE INDEX runner_one_unreleased_writer ON runner_leases(workspace_id) WHERE state!='released'`,
  `CREATE TRIGGER runner_lease_insert BEFORE INSERT ON runner_leases WHEN NEW.state!='active' OR NEW.revision!=1 OR NEW.sequence!=0 OR NEW.dispatched!=0 OR NOT EXISTS(SELECT 1 FROM runner_workspaces w WHERE w.principal_id=NEW.principal_id AND w.id=NEW.workspace_id AND w.generation=NEW.generation AND w.state='ready') BEGIN SELECT RAISE(ABORT,'new lease workspace/state mismatch'); END`,
  `CREATE TRIGGER runner_lease_update BEFORE UPDATE ON runner_leases WHEN NEW.principal_id!=OLD.principal_id OR NEW.id!=OLD.id OR NEW.workspace_id!=OLD.workspace_id OR NEW.generation!=OLD.generation OR NEW.scope_id!=OLD.scope_id OR NEW.actor_id!=OLD.actor_id OR NEW.owner_id!=OLD.owner_id OR NEW.owner_epoch!=OLD.owner_epoch OR NEW.operation!=OLD.operation OR NEW.hard_deadline!=OLD.hard_deadline OR NEW.revision!=OLD.revision+1 OR NEW.sequence<OLD.sequence OR NEW.stop_epoch<OLD.stop_epoch OR NEW.dispatched<OLD.dispatched OR NEW.updated_at<OLD.updated_at OR OLD.state='released' OR (OLD.state!='active' AND NEW.state='active') OR (OLD.state!='active' AND NEW.expires_at!=OLD.expires_at) BEGIN SELECT RAISE(ABORT,'lease identity/state/revision mismatch'); END`,
  `CREATE TABLE runner_stop_observations(principal_id TEXT NOT NULL, id TEXT NOT NULL, lease_id TEXT NOT NULL, workspace_id TEXT NOT NULL, generation INTEGER NOT NULL, owner_id TEXT NOT NULL, owner_epoch INTEGER NOT NULL, stop_epoch INTEGER NOT NULL CHECK(stop_epoch IN (0,1)), kind TEXT NOT NULL CHECK(kind IN ('synthetic','fixed_guest_fixture')), handles_signaled INTEGER NOT NULL CHECK(handles_signaled IN (0,1)), job_empty INTEGER NOT NULL CHECK(job_empty IN (0,1)), writes_stable INTEGER NOT NULL CHECK(writes_stable IN (0,1)), observed_at INTEGER NOT NULL CHECK(observed_at BETWEEN 0 AND 9007199254740991), detail TEXT NOT NULL CHECK(json_valid(detail) AND length(CAST(detail AS BLOB))<=65536), PRIMARY KEY(principal_id,id), FOREIGN KEY(${binding}) REFERENCES runner_leases(${binding.replace('lease_id','id')})) STRICT`,
  `CREATE TRIGGER runner_observation_update BEFORE UPDATE ON runner_stop_observations BEGIN SELECT RAISE(ABORT,'stop observation is immutable'); END`,
  `CREATE TRIGGER runner_observation_delete BEFORE DELETE ON runner_stop_observations BEGIN SELECT RAISE(ABORT,'stop observation is immutable'); END`,
  `CREATE TRIGGER runner_lease_release BEFORE UPDATE ON runner_leases WHEN NEW.state='released' AND NOT EXISTS(SELECT 1 FROM runner_stop_observations o JOIN runner_workspaces w ON w.principal_id=NEW.principal_id AND w.id=NEW.workspace_id JOIN runner_profiles p ON p.principal_id=w.principal_id AND p.id=w.profile_id AND p.revision=w.profile_revision WHERE o.principal_id=NEW.principal_id AND o.id=NEW.observation_id AND o.lease_id=NEW.id AND o.workspace_id=NEW.workspace_id AND o.generation=NEW.generation AND o.owner_id=NEW.owner_id AND o.owner_epoch=NEW.owner_epoch AND o.stop_epoch=NEW.stop_epoch AND o.kind=p.kind AND o.handles_signaled=1 AND o.job_empty=1 AND o.writes_stable=1) BEGIN SELECT RAISE(ABORT,'matching complete stop observation required'); END`,
  `CREATE TRIGGER runner_workspace_reuse BEFORE UPDATE ON runner_workspaces WHEN (NEW.generation!=OLD.generation OR NEW.state='ready') AND EXISTS(SELECT 1 FROM runner_leases l WHERE l.workspace_id=OLD.id AND l.state!='released') BEGIN SELECT RAISE(ABORT,'unreleased writer blocks workspace reuse'); END`,
  `CREATE TRIGGER runner_lease_delete BEFORE DELETE ON runner_leases BEGIN SELECT RAISE(ABORT,'lease history cannot be deleted'); END`,
];
export interface RunnerReader {
  getProfile(principalId: string, id: string, revision: bigint): RunnerProfile | undefined;
  getWorkspace(principalId: string, id: string): RunnerWorkspace | undefined;
  getLease(principalId: string, id: string): RunnerLease | undefined;
  listLeases(principalId: string): RunnerLease[];
  getObservation(principalId: string, id: string): RunnerStopObservation | undefined;
}
export interface RunnerTransaction extends RunnerReader {
  insertProfile(profile: RunnerProfile): void;
  insertWorkspace(workspace: RunnerWorkspace): void;
  updateWorkspace(workspace: RunnerWorkspace, expectedGeneration: bigint): void;
  insertLease(lease: RunnerLease): void;
  updateLease(lease: RunnerLease, expectedRevision: bigint): void;
  insertObservation(observation: RunnerStopObservation): void;
}
type Row = Record<string, SQLOutputValue>;
type Get = (sql: string, ...args: SQLInputValue[]) => Row | undefined;
type All = (sql: string, ...args: SQLInputValue[]) => Row[];
type Run = (sql: string, ...args: SQLInputValue[]) => { changes: number | bigint };
const n = (value: SQLOutputValue | undefined): number => Number(value);
const profileRow = (r: Row): RunnerProfile => ({ principalId:r.principal_id as string,id:r.id as string,revision:r.revision as bigint,digest:r.digest as string,kind:r.kind as RunnerEvidenceKind,isolationId:r.isolation_id as string,ttlMs:n(r.ttl_ms) });
const workspaceRow = (r: Row): RunnerWorkspace => ({principalId:r.principal_id as string,id:r.id as string,profileId:r.profile_id as string,profileRevision:r.profile_revision as bigint,profileDigest:r.profile_digest as string,snapshotDigest:r.snapshot_digest as string,writeSetDigest:r.write_set_digest as string,isolationId:r.isolation_id as string,generation:r.generation as bigint,state:r.state as RunnerWorkspace['state']});
const leaseRow = (r: Row): RunnerLease => ({principalId:r.principal_id as string,id:r.id as string,workspaceId:r.workspace_id as string,generation:r.generation as bigint,scopeId:r.scope_id as string,actorId:r.actor_id as string,ownerId:r.owner_id as string,ownerEpoch:r.owner_epoch as bigint,stopEpoch:r.stop_epoch as bigint,operation:'verify',state:r.state as RunnerLease['state'],revision:r.revision as bigint,sequence:r.sequence as bigint,expiresAt:n(r.expires_at),hardDeadline:n(r.hard_deadline),updatedAt:n(r.updated_at),dispatched:r.dispatched===1n,observationId:r.observation_id as string|null});
const observationRow = (r: Row): RunnerStopObservation => ({principalId:r.principal_id as string,id:r.id as string,leaseId:r.lease_id as string,workspaceId:r.workspace_id as string,generation:r.generation as bigint,ownerId:r.owner_id as string,ownerEpoch:r.owner_epoch as bigint,stopEpoch:r.stop_epoch as bigint,kind:r.kind as RunnerEvidenceKind,handlesSignaled:r.handles_signaled===1n,jobEmpty:r.job_empty===1n,writesStable:r.writes_stable===1n,observedAt:n(r.observed_at),detail:r.detail as string});

/** SQL capabilities remain scoped to the parent LedgerStore callback. No independent connection. */
export class RunnerAccess implements RunnerTransaction {
  readonly #get: Get; readonly #all: All; readonly #run: Run; readonly #conflict: () => never;
  constructor(get: Get, all: All, run: Run, conflict: () => never) {this.#get=get;this.#all=all;this.#run=run;this.#conflict=conflict;}
  getProfile(p:string,id:string,v:bigint): RunnerProfile|undefined {const r=this.#get('SELECT * FROM runner_profiles WHERE principal_id=? AND id=? AND revision=?',p,id,v);return r&&profileRow(r);}
  getWorkspace(p:string,id:string): RunnerWorkspace|undefined {const r=this.#get('SELECT * FROM runner_workspaces WHERE principal_id=? AND id=?',p,id);return r&&workspaceRow(r);}
  getLease(p:string,id:string): RunnerLease|undefined {const r=this.#get('SELECT * FROM runner_leases WHERE principal_id=? AND id=?',p,id);return r&&leaseRow(r);}
  listLeases(p:string): RunnerLease[] {return this.#all('SELECT * FROM runner_leases WHERE principal_id=? ORDER BY id',p).map(leaseRow);}
  getObservation(p:string,id:string): RunnerStopObservation|undefined {const r=this.#get('SELECT * FROM runner_stop_observations WHERE principal_id=? AND id=?',p,id);return r&&observationRow(r);}
  insertProfile(r:RunnerProfile):void {this.#run('INSERT INTO runner_profiles VALUES(?,?,?,?,?,?,?)',r.principalId,r.id,r.revision,r.digest,r.kind,r.isolationId,r.ttlMs);}
  insertWorkspace(r:RunnerWorkspace):void {this.#run('INSERT INTO runner_workspaces VALUES(?,?,?,?,?,?,?,?,?,?)',r.principalId,r.id,r.profileId,r.profileRevision,r.profileDigest,r.snapshotDigest,r.writeSetDigest,r.isolationId,r.generation,r.state);}
  updateWorkspace(r:RunnerWorkspace,expected:bigint):void {const old=this.getWorkspace(r.principalId,r.id);if(!old||(['profileId','profileRevision','profileDigest','snapshotDigest','writeSetDigest','isolationId'] as const).some(k=>old[k]!==r[k]))this.#conflict();if(this.#run('UPDATE runner_workspaces SET generation=?,state=? WHERE principal_id=? AND id=? AND generation=?',r.generation,r.state,r.principalId,r.id,expected).changes!==1n)this.#conflict();}
  insertLease(r:RunnerLease):void {this.#run('INSERT INTO runner_leases VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',r.principalId,r.id,r.workspaceId,r.generation,r.scopeId,r.actorId,r.ownerId,r.ownerEpoch,r.stopEpoch,r.operation,r.state,r.revision,r.sequence,r.expiresAt,r.hardDeadline,r.updatedAt,r.dispatched?1:0,r.observationId);}
  updateLease(r:RunnerLease,expected:bigint):void {const old=this.getLease(r.principalId,r.id);if(!old||(['workspaceId','generation','scopeId','actorId','ownerId','ownerEpoch','operation','hardDeadline'] as const).some(k=>old[k]!==r[k]))this.#conflict();if(this.#run('UPDATE runner_leases SET stop_epoch=?,state=?,revision=?,sequence=?,expires_at=?,updated_at=?,dispatched=?,observation_id=? WHERE principal_id=? AND id=? AND revision=?',r.stopEpoch,r.state,r.revision,r.sequence,r.expiresAt,r.updatedAt,r.dispatched?1:0,r.observationId,r.principalId,r.id,expected).changes!==1n)this.#conflict();}
  insertObservation(r:RunnerStopObservation):void {this.#run('INSERT INTO runner_stop_observations VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',r.principalId,r.id,r.leaseId,r.workspaceId,r.generation,r.ownerId,r.ownerEpoch,r.stopEpoch,r.kind,r.handlesSignaled?1:0,r.jobEmpty?1:0,r.writesStable?1:0,r.observedAt,r.detail);}
}
